### ISSUE TITLE
Teams Bot Proactive messages : ETIMEDOUT error

### ISSUE THREAD

**Issue by udaya-reddy** [OfficeDev/Microsoft-Teams-Samples#1148]
`
await context.adapter.continueConversation(ref, async (context) => {
                 await context.sendActivity("Proactive hello.");
             });
`

This block throws ETIMEDOUT exception when trying to send notification on teams for multiple users in the org. It send for some users but for many it times out.

How to ensure this works for all users?

**Comment by Vikram-MSFT** [comment]
Hello @udaya-reddy we will investigate this issue and get back to you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @udaya-reddy - Could you please confirm for how many users you are trying to send the notification in one go?

**You can implement retry logic:** 
If the ETIMEDOUT exception is intermittent, you can implement retry logic in your code to handle transient failures. This can help in cases where the issue is temporary and resolves itself after a short period of time. You can use exponential backoff or other retry strategies to gradually increase the delay between retries.

**Comment by udaya-reddy** [comment]
ok, will implement the retry logic.  so around 500 users.

**Comment by udaya-reddy** [comment]
This did not help. It stops after sending to employees up alphabet D.. looks like there is a rate limit. Is there a way to overcome this? how do we notify all employees in the org ? we have more than 4000 users.

**Comment by ChetanSharma-msft** [comment]
Hello @udaya-reddy - Please refer this documentation: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit

**Comment by udaya-reddy** [comment]
Please note that we are sending 1 message per user and therefore there seem to be no violation of any rate limits specified in the above document. 
Requirement is to send to all employees org wide notification using proactive bot message.

**Comment by udaya-reddy** [comment]
Any update? notifications to employees are failing. not sure what to do @ChetanSharma-msft ..

**Comment by ChetanSharma-msft** [comment]
Hello @udaya-reddy - Sorry for delay in response.
We are actively checking on it and let you know the updates.

**Comment by udaya-reddy** [comment]
Please note we also get connect ECONNREFUSED 52.114.159.141:443

**Comment by ChetanSharma-msft** [comment]
Hello @udaya-reddy - Sorry for delay in response.
Regarding **ETIMEDOUT error**,

To ensure that the proactive message works for all users in the organization without timing out, you can make the following changes to your code:

**Increase the timeout value:** 
By default, the timeout value for sending proactive messages is set to a lower value. You can increase the timeout value to allow more time for the messages to be sent. You can modify the `continueConversation` method to include a longer timeout value. For example:

`const { TurnContext, BotFrameworkAdapter } = require('botbuilder');

// Create adapter
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});

// Create TurnContext
const conversationReference = {
    user: { id: '<user-id>' },
    bot: { id: '<bot-id>' },
    conversation: { id: '<conversation-id>' },
    channelId: '<channel-id>',
    serviceUrl: '<service-url>'
};

const message = { text: 'Hello, World!' };
const timeout = 60000; // Timeout in milliseconds
const delayBetweenCalls = 5000; // Delay in milliseconds

async function continueConversation() {
    try {
        const turnContext = new TurnContext(adapter, await adapter.getUserToken(conversationReference, process.env.ConnectionName));
        await adapter.continueConversation(conversationReference, async (context) => {
            await context.sendActivity(message);
        });
    } catch (error) {
        console.error('An error occurred:', error);
        // Handle errors
    }
}

// Function to call continueConversation with delay
async function callWithDelay() {
    while (true) {
        await continueConversation();
        await delay(delayBetweenCalls);
    }
}

// Delay function
function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

// Call the function
callWithDelay();
`

**Implement batching:** 
Instead of sending proactive messages to all users at once, you can implement batching to send messages in smaller groups. This can help prevent timeouts and improve the overall performance. You can modify your code to send messages to a limited number of users at a time and then wait for a certain period before sending messages to the next group. 

Here's an example:

`const { TurnContext, BotFrameworkAdapter } = require('botbuilder');

// Create adapter
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});

// Create TurnContext
const conversationReference = {
    user: { id: '<user-id>' },
    bot: { id: '<bot-id>' },
    conversation: { id: '<conversation-id>' },
    channelId: '<channel-id>',
    serviceUrl: '<service-url>'
};

const message = { text: 'Hello, World!' };
const timeout = 60000; // Timeout in milliseconds
const batchSize = 10; // Number of conversations to handle in each batch
const delayBetweenBatches = 5000; // Delay in milliseconds between batches

async function continueConversationBatch(batchSize) {
    try {
        const turnContext = new TurnContext(adapter, await adapter.getUserToken(conversationReference, process.env.ConnectionName));
        for (let i = 0; i < batchSize; i++) {
            await adapter.continueConversation(conversationReference, async (context) => {
                await context.sendActivity(message);
            });
        }
    } catch (error) {
        console.error('An error occurred:', error);
        // Handle errors
    }
}

// Function to add delay between batches
function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

// Function to call continueConversation in batches
async function callInBatches(batchSize, totalConversations, delayBetweenBatches) {
    const numBatches = Math.ceil(totalConversations / batchSize);
    for (let i = 0; i < numBatches; i++) {
        await continueConversationBatch(batchSize);
        if (i < numBatches - 1) {
            await delay(delayBetweenBatches);
        }
    }
}

// Call the function with batch size, total conversations, and delay between batches
callInBatches(batchSize, 100, delayBetweenBatches); // Adjust the total conversations and delay as per your requirement
`

By implementing batching, you can send messages to a limited number of users at a time and introduce a delay between batches to avoid timeouts.
These changes should help ensure that the proactive messages are sent to all users in the organization without timing out.

Regarding **ECONNREFUSED 52.114.159.141:443**,

The error message "**ECONNREFUSED**" typically indicates that the **connection to the specified IP address and port is being refused by the server**. In this case, the IP address 52.114.159.141 appears to be the server to which your application is attempting to connect, likely a Microsoft server as it's on the Azure network.

Here are a few potential reasons for receiving this error:

**Firewall or Network Configuration:** 
The server might be blocking incoming connections on port 443 (HTTPS). Ensure that there are no firewall rules or network configurations blocking the connection.

**Service Unavailable or Maintenance:** 
The server could be temporarily unavailable due to maintenance or other reasons. You can check the service status provided by Microsoft Azure or the service provider for any known issues.

**Incorrect URL or Endpoint:** 
Ensure that the URL or endpoint you are trying to connect to is correct and properly configured. Double-check the service URL or IP address to ensure accuracy.

**Temporary Network Issues:** 
Temporary network issues or internet connectivity problems can also lead to connection refusal. Try again later to see if the issue persists.

To troubleshoot further, you may want to verify the correctness of the IP address, ensure that the server is operational, and check for any **network-related issues** on your end.
