### ISSUE TITLE
How to generate src token

### ISSUE THREAD

**Issue by yashgandhi-32** [OfficeDev/Microsoft-Teams-Samples#1410]
I have assigned my apps permissions from teams dev portal ... 

now I am suing this API to generate token 

```
https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token

with

scope: https://graph.microsoft.com/.default
grant_type: client_credentials
client_id: ''
client_secret: ''

```

when I use 
https://graph.microsoft.com/v1.0/teams/{chatid}/members but I get this error

```
{
    "error": {
        "code": "Forbidden",
        "message": "Missing role permissions on the request. API requires one of 'TeamMember.Read.All, TeamMember.ReadWrite.All, Group.Read.All, Group.ReadWrite.All, TeamMember.Read.Group, Member.Read.Group'. Roles on the request ''. Resource specific consent grants on the request ''.",
        "innerError": {
            "date": "2024-10-04T08:08:43",
            "request-id": "335dc012-b09b-4d3-ec390f141b53",
            "client-request-id": "335dc012-b09b-4daed3-ec390f141b53"
        }
    }
}

```
See below screenshot its already assigned ... can you help me how to make it work or I am doing something wrong ?

<img width="1161" alt="Screenshot 2024-10-04 at 3 07 30 PM" src="https://github.com/user-attachments/assets/62a86dc6-515c-40cb-bb4c-833277c29346">

**Comment by Nivedipa-MSFT** [comment]
@yashgandhi-32 - Thanks for reporting your issue. We will check this and update you soon.

**Comment by yashgandhi-32** [comment]
@Nivedipa-MSFT Any update ?

**Comment by Nivedipa-MSFT** [comment]
@yashgandhi-32 - There is no such type of API mentioned in the document.
`https://graph.microsoft.com/v1.0/teams/{chatid}/members`

Are you trying teamid instead of chatid?
`https://graph.microsoft.com/v1.0/teams/{teamid}/members`
 requires the TeamMember.Read.Group permission, which uses [resource-specific consent](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent).
Ref Doc: https://learn.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http

Could you please get the set of resource-specific permissions consented for the apps installed in the specified team?
https://learn.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&tabs=http&preserve-view=true#example-4-get-the-set-of-resource-specific-permissions-consented-for-the-apps-installed-in-the-specified-team

If the permissions are not available in the above API, you need to follow these steps:


1. [Add RSC permissions to your Teams app](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent#add-rsc-permissions-to-your-teams-app)
2. [Install your app in a team, chat, or user](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent#install-your-app-in-a-team-chat-or-user)
3. [Verify app RSC permission granted to your app](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent#verify-app-rsc-permission-granted-to-your-app)

**Comment by yashgandhi-32** [comment]
@Nivedipa-MSFT

I have a below questions regarding the implementation you mentioned:

1. I tried to get the `teamId` from the activity when my app is installed in any team/channel using the following code:
   ```javascript
   const teamId = context.activity.conversation.id;
This returns an ID that looks something like **19:ziLdARqGQ1Mdfjfpzl9BO3qb9FakOa1fEMIP8Tt01gk01@thread.tacv2**. Is this the channel ID or the team ID? If it's not the correct one, could you please explain how to obtain the teamId when someone installs my app in any channel?

2. To update RSC permissions, we can only do this via app upload. Alternatively, if we go to the [Microsoft Teams Developer Portal](https://dev.teams.microsoft.com/apps), can we update permissions there as well? If we do so, will those changes also reflect in the app?

Thank you!

**Comment by yashgandhi-32** [comment]
@Nivedipa-MSFT ... Could you pls answer

**Comment by Nivedipa-MSFT** [comment]
@yashgandhi-32 - Apologies for the delay. 
The context.activity.conversation.id you mentioned is the channel ID, not the team ID. To get the team ID, you can use the following approach:
[Teams Specific Context for Bot - Teams | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Fbots%2Fhow-to%2Fget-teams-context%3Ftabs%3Ddotnet%23get-teams-details&data=05%7C02%7Cv-nivedipasu%40microsoft.com%7C26cd1f46295f4bb4569208dce920e901%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638641574820302728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C80000%7C%7C%7C&sdata=NqZjJDWaRF8AYX2ysvjYRG5GFysS3bejYWZX3fBYLcY%3D&reserved=0)

Regarding updating RSC (Resource-Specific Consent) permissions, you can indeed update them via the Microsoft Teams Developer Portal. When you update permissions there, those changes will reflect in the app. Here’s how you can do it:

1. Go to the Microsoft Teams Developer Portal.
2. Navigate to your app and select the "Permissions" tab.
3. Update the RSC permissions as needed.
 

Ref Doc:
1. https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent
2. https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/app-permissions/teams-app-permissions

**Comment by yashgandhi-32** [comment]
But i tried and it seems no changes are reflected .. is there any time it take to sync changes maybe ? I added some permissions from dev team portal but i got error when i tried to read list of members

**Comment by Nivedipa-MSFT** [comment]
@yashgandhi-32 - Could you please share the error that you are getting, or are you getting the same error as previously mentioned?
