### ISSUE TITLE
App-SSO is not working on Single Tenant environment

### ISSUE THREAD

**Issue by diegoriera** [OfficeDev/Microsoft-Teams-Samples#711]
I tried to use the https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso on single tenant however it is returning 400 from POST https://login.microsoftonline.com/botframework.com/oauth2/token

This sample from Azure team is working well with Single Tenant, it indicates that, the bot is properly configured. https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/02.echo-bot/AdapterWithErrorHandler.cs

![image](https://user-images.githubusercontent.com/15849138/218828528-bb8ec97e-44b5-4b76-abd8-c02209de5052.png)

**Comment by Prasad-MSFT** [comment]
@diegoriera - The error happens if there is a mismatch between the tenant where your app is registered and where you have stated in either the application code or the portal that your application is registered. Please ensure that your application ID/client ID are matching on both sides and all of the values set in your app settings match what you have in the portal.

In case, after configuring the correct Client ID you still get this error, you need to construct the below URL and provide it to the Global administrator of your tenant, who will have to consent after successfully signing in.
`https://login.microsoftonline.com/common/adminconsent?client_id=your_client_id`

**Comment by diegoriera** [comment]
I am using dedicated App registration, one for bot, one for user auth.

It is not clear what id should be used on each property on appsettings as well as what id shoud be used on Application ID URI

**Comment by Prasad-MSFT** [comment]
@diegoriera - You should use the AAD App Id which you created in first place. The application id URI should be in below format: `api://fully-qualified-domain-name/botid-{AppID}`
The {AppID} is same AAD App id which was created.

Please refer this doc: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation-sso-quickstart/BotSSOSetup.md

**Comment by diegoriera** [comment]
As agreed on Teams, you will check it internally as per test result:
'Failed to acquire token for client credentials. (AADSTS700016: Application with identifier 'd8e23ce2-0191-4d30-ad17-02547478fba7' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by ChetanSharma-msft** [comment]
Hello @diegoriera - We are also experiencing the same issue so we are checking with the engineering team and added you also in that internal discussion.

**Comment by Prasad-MSFT** [comment]
Adding below two in appsettings.json , it worked.
```
"MicrosoftAppType": "SingleTenant",
"MicrosoftAppTenantId": "<tenant-id>"
```

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
