### ISSUE TITLE
SSO OAuthPrompt dialog is returning V1 token

### ISSUE THREAD

**Issue by bindeshv** [OfficeDev/Microsoft-Teams-Samples#805]
I am following the article for SSO in the Teams bot => https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso and using the sample code bot-conversation-sso-quickstart(JS). 

While running the sample and my own version of the implementation in my bot (using the method specified in the sample) I see the access token I receive from OAuthPrompt Dialog is V1 token. 

Is there a way to get V2 token from the prompt.  The intention is to make a backend Web API(custom) call and pass the access token for validation. However, I am unable to authenticate and verify the token and the error I get is: 
expected issuer is login.microsoftonline.com whereas the issuer is sts.windows.net. I have already configured the AAD app for v2 token via the property "accessTokenAcceptedVersion":2.

**Comment by Prasad-MSFT** [comment]
To get v2.0 token, you need to change your application's Manifest like below:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/6600b4d5-874c-4ca7-a2be-d0a8f73dea13)

If you have already done that, try using the Azure AD V2 endpoint instead of the V1 endpoint (e.g.  https://login.microsoftonline.com/tenant.onmicrosoft.com/oauth2/v2.0/token)

**Comment by bindeshv** [comment]
Thanks, is there a way to do this via OAuthPrompt? I have the following code for SSO in my bot:

export class AuthDialog extends ComponentDialog {
    constructor() {
        super(AUTH_DIALOG);
        this.addDialog(new **OAuthPrompt**(OAUTH_PROMPT, {
            connectionName: process.env.ConnectionName,
            text: 'Please Sign In',
            title: 'Sign In',
            timeout: 300000
        }));
        this.addDialog(new ConfirmPrompt(CONFIRM_PROMPT));
        this.addDialog(new WaterfallDialog(MAIN_WATERFALL_DIALOG, [
            this.promptStep.bind(this),
            this.loginStep.bind(this),
            this.ensureOAuth.bind(this),
            this.displayToken.bind(this)
        ]));
        this.initialDialogId = MAIN_WATERFALL_DIALOG;
    }

**Comment by bindeshv** [comment]
Debugging more on this I found out that when I call the OAuthPrompt dialog, I receive a Graph token where the audience, issuer and version is set as follows. 

`  {
"aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/{my-tenant-id}/",
  "ver": "1.0"
}
`
When I use a OIDC validator for token at the backend, I get a mismatch error. I believe I will have to make an explicit request to my AAD app to get v2 token? 
I believe, if this is the case then the following documentation needs to be corrected-  https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=bot-app

which states in the **Validate access token** section: 

_Keep in mind the following guidelines when validating the token:

Valid SSO tokens are issued by Azure AD. The iss claim in the token should start with this value.
**The token's aud1 parameter will be set to the app ID generated during Azure AD app registration.
The token's scp parameter will be set to access_as_user.**_

Coz' we never receive this from the SSO, instead we receive graph app as the issuer. Or is it some configuration issue on my AAD app? 

Please let me know in case I have missed something.

**Comment by bindeshv** [comment]
On further debugging this, I found out that the OAuthPrompt dialog requests MSGraph via the OAuth connection settings in the Bot Configuration and returns a graph token which has the following information in it: 

```
{
'iss': 'https://sts.windows.net/{my-tenant-id}', 
'aud': '00000003-0000-0000-c000-000000000000', // ms-graph-id
'ver': 1, 
'scp':  "email openid profile User.Read"
}
```
And I can't validate this with OIDC parser at the backend, since I always get a mismatched error relating to audience. In which case, I believe, I need to make an explicit request to get a new access token to be passed to the backend API? 

If this is correct, then the following documentation -https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=bot-app where in the **Validate access token** section, it states the below is incorrect: 

`Keep in mind the following guidelines when validating the token:

Valid SSO tokens are issued by Azure AD. The iss claim in the token should start with this value.
**The token's aud1 parameter will be set to the app ID generated during Azure AD app registration**.
**The token's scp parameter will be set to access_as_user**.
`
Since the OAuthPrompt, in essence returns a graph token, which can be used to query user information and the token headers are set for V1 instead of the AAD app that we use. 

Please let me know if this is correct understanding or if there is something that I need to change in my configuration for AAD app.

**Comment by Prasad-MSFT** [comment]
For details about validate the access token, see [Validate tokens](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validate-tokens).

**Comment by ChetanSharma-msft** [comment]
Hello @bindeshv - Sorry for the trouble.
Could you please confirm whether your issue has resolved or not?

As per my understand, this issue is because of "ValidIssuer" is not configured properly in your application.
Expected issuer is login.microsoftonline.com whereas the issuer is sts.windows.net.

Could you please refer these:
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-register-aad?tabs=windows
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=bot-app

https://stackoverflow.com/questions/59790209/issuer-in-access-token-from-azure-active-directory-is-https-sts-windows-net-wh

Also, please confirm whether you are getting v2 token after running below sample?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js

If you still have any query, please feel free to ask.

**Comment by ChetanSharma-msft** [comment]
Hello @bindeshv - We are closing this issue for now, please feel free to reopen it, if required.
